info:
  app:
    version: ^project.version^

server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sakaretroweb@gmail.com
    password: kscp rjqo snzl raph
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  datasource:
    url: jdbc:postgresql://localhost:5432/comment
    username: postgres
    password: mysecretpassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

socket:
  host : localhost
  port : 8092